name: SketchMap
version: 2.0
main: net.aerulion.sketchmap.Main
api-version: 1.16
depend: [Nucleus]
commands:
  sketchmap:
    description: SketchMap main command.
permissions:
  sketchmap.use:
    description: Allows the player to use the plugin.
    default: op